### ISSUE TITLE
stub-package for python modules or extensions?

### ISSUE THREAD

**Issue by szabolcsdombi** [ethanhs/stub-package#1]
Hi, thank you very much for providing examples for [PEP 561](https://peps.python.org/pep-0561/)

Just for curiosity I have installed this library with

```
pip install https://github.com/ethanhs/stub-package/archive/refs/heads/master.zip
```

and found that my VSCode can see the typehints:

![image](https://user-images.githubusercontent.com/11232402/199741624-0b98572f-f2e7-4b0f-a4ba-7a0625639359.png)

despite there is no `typedpkg` installed.

I am not interested in type hinting packages. I usually make Python extensions or modules with type hints in .pyi stub files.
in this context:
- packages are folders of python code with or without an `__init__.py`.
- modules are `modulename.py` files.
- extensions are `mymodule.___.pyd` or `mymodule.___.so` files.

This repository is a great example to add stub files for packages, but would it be correct to use it for modules or extensions?

I currently have:

```py
setup(
    name='mymodule',
    ext_modules=[Extension(name='mymodule', ...)],
    data_files=[('.', ['mymodule.pyi'])],
)
```

This is obviously not correct as '.' is not a package, but it seemed to work and I used it [here](https://github.com/szabolcsdombi/zengl/blob/67afe6f6ee96a2cfef8d6a299869b4b36675573d/setup.py#L26-L28).

Moving `mymodule.pyi` to `mymodule-stubs/__init__.pyi` and changing the setup code to:

```py
setup(
    name='mymodule',
    ext_modules=[Extension(name='mymodule', ...)],
    package_data={'mymodule-stubs': ['__init__.pyi']},
    packages=['mymodule-stubs'],
)
```

This might be also inappropiate as mymodule is an extension not a package.

**Comment by emmatyping** [comment]
Hi, PEP 561 doesn't support single module packages, see https://peps.python.org/pep-0561/#packaging-type-information

I would recommend putting a folder of the same name of the module that includes either an `__init__.pyi` or making a separate `-stubs` package if you are worried about the folder conflicting with the module. Hopefully that makes sense?

**Comment by szabolcsdombi** [comment]
> This PEP does not support distributing typing information as part of module-only distributions or single-file modules within namespace packages.
> The single-file module should be refactored into a package and indicate that the package supports typing as described above.

Indeed I missed this information.

---

> I would recommend putting a folder of the same name of the module that includes either an __init__.pyi or making a separate -stubs package if you are worried about the folder conflicting with the module. Hopefully that makes sense?

Makes sense. The package folder with `-stubs` ending sounds safer.

This works so far for an [extension only distribution](https://github.com/szabolcsdombi/python-extension-with-stub).

One thing that still bothers me is the naming. According to https://github.com/pypa/distutils/issues/108#issuecomment-1011288639 the **folder name** shoud contain an underscore while the **packages** and **package_data** entries should contain dash.

Is this correct?

**Comment by emmatyping** [comment]
Henry is incorrect there, see for example mypy's test data for stub packages: https://github.com/python/mypy/tree/master/test-data/packages/typedpkg-stubs

The point of the `-stubs` prefix is that it is meant only for type-checkers, it shouldn't be importable.

**Comment by szabolcsdombi** [comment]
Thank you for the clarification!
